package modelo.pojo;
// Generated 10-15-2016 03:51:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;

/**
 * Adjunto generated by hbm2java
 */
public class Adjunto  implements java.io.Serializable {


     private BigDecimal idAdjunto;
     private Denuncia denuncia;
     private Blob imagen;
     private Blob video;

    public Adjunto() {
    }

	
    public Adjunto(BigDecimal idAdjunto) {
        this.idAdjunto = idAdjunto;
    }
    public Adjunto(BigDecimal idAdjunto, Denuncia denuncia, Blob imagen, Blob video) {
       this.idAdjunto = idAdjunto;
       this.denuncia = denuncia;
       this.imagen = imagen;
       this.video = video;
    }
   
    public BigDecimal getIdAdjunto() {
        return this.idAdjunto;
    }
    
    public void setIdAdjunto(BigDecimal idAdjunto) {
        this.idAdjunto = idAdjunto;
    }
    public Denuncia getDenuncia() {
        return this.denuncia;
    }
    
    public void setDenuncia(Denuncia denuncia) {
        this.denuncia = denuncia;
    }
    public Blob getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Blob imagen) {
        this.imagen = imagen;
    }
    public Blob getVideo() {
        return this.video;
    }
    
    public void setVideo(Blob video) {
        this.video = video;
    }




}


