package modelo.pojo;
// Generated 10-15-2016 03:51:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private BigDecimal idCategoria;
     private CatalogoCategorias catalogoCategorias;
     private Denuncia denuncia;
     private String nombreCategoria;
     private Set denuncias = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(BigDecimal idCategoria, String nombreCategoria) {
        this.idCategoria = idCategoria;
        this.nombreCategoria = nombreCategoria;
    }
    public Categoria(BigDecimal idCategoria, CatalogoCategorias catalogoCategorias, Denuncia denuncia, String nombreCategoria, Set denuncias) {
       this.idCategoria = idCategoria;
       this.catalogoCategorias = catalogoCategorias;
       this.denuncia = denuncia;
       this.nombreCategoria = nombreCategoria;
       this.denuncias = denuncias;
    }
   
    public BigDecimal getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(BigDecimal idCategoria) {
        this.idCategoria = idCategoria;
    }
    public CatalogoCategorias getCatalogoCategorias() {
        return this.catalogoCategorias;
    }
    
    public void setCatalogoCategorias(CatalogoCategorias catalogoCategorias) {
        this.catalogoCategorias = catalogoCategorias;
    }
    public Denuncia getDenuncia() {
        return this.denuncia;
    }
    
    public void setDenuncia(Denuncia denuncia) {
        this.denuncia = denuncia;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public Set getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set denuncias) {
        this.denuncias = denuncias;
    }




}


