package modelo.pojo;
// Generated 10-15-2016 03:51:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Denuncia generated by hbm2java
 */
public class Denuncia  implements java.io.Serializable {


     private BigDecimal idDenuncia;
     private Categoria categoria;
     private Denunciante denunciante;
     private Departamento departamento;
     private Estado estado;
     private String descripcion;
     private String direccion;
     private Set adjuntos = new HashSet(0);
     private Set categorias = new HashSet(0);
     private Set denunciantes = new HashSet(0);
     private Set estados = new HashSet(0);

    public Denuncia() {
    }

	
    public Denuncia(BigDecimal idDenuncia, String descripcion) {
        this.idDenuncia = idDenuncia;
        this.descripcion = descripcion;
    }
    public Denuncia(BigDecimal idDenuncia, Categoria categoria, Denunciante denunciante, Departamento departamento, Estado estado, String descripcion, String direccion, Set adjuntos, Set categorias, Set denunciantes, Set estados) {
       this.idDenuncia = idDenuncia;
       this.categoria = categoria;
       this.denunciante = denunciante;
       this.departamento = departamento;
       this.estado = estado;
       this.descripcion = descripcion;
       this.direccion = direccion;
       this.adjuntos = adjuntos;
       this.categorias = categorias;
       this.denunciantes = denunciantes;
       this.estados = estados;
    }
   
    public BigDecimal getIdDenuncia() {
        return this.idDenuncia;
    }
    
    public void setIdDenuncia(BigDecimal idDenuncia) {
        this.idDenuncia = idDenuncia;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Denunciante getDenunciante() {
        return this.denunciante;
    }
    
    public void setDenunciante(Denunciante denunciante) {
        this.denunciante = denunciante;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getAdjuntos() {
        return this.adjuntos;
    }
    
    public void setAdjuntos(Set adjuntos) {
        this.adjuntos = adjuntos;
    }
    public Set getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Set categorias) {
        this.categorias = categorias;
    }
    public Set getDenunciantes() {
        return this.denunciantes;
    }
    
    public void setDenunciantes(Set denunciantes) {
        this.denunciantes = denunciantes;
    }
    public Set getEstados() {
        return this.estados;
    }
    
    public void setEstados(Set estados) {
        this.estados = estados;
    }




}


