package modelo.pojo;
// Generated 10-15-2016 03:51:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Denunciante generated by hbm2java
 */
public class Denunciante  implements java.io.Serializable {


     private BigDecimal idDenunciante;
     private Denuncia denuncia;
     private String nombreDenunciante;
     private String correoDenunciante;
     private String telefonoDenunciante;
     private Set denuncias = new HashSet(0);

    public Denunciante() {
    }

	
    public Denunciante(BigDecimal idDenunciante, String nombreDenunciante, String correoDenunciante, String telefonoDenunciante) {
        this.idDenunciante = idDenunciante;
        this.nombreDenunciante = nombreDenunciante;
        this.correoDenunciante = correoDenunciante;
        this.telefonoDenunciante = telefonoDenunciante;
    }
    public Denunciante(BigDecimal idDenunciante, Denuncia denuncia, String nombreDenunciante, String correoDenunciante, String telefonoDenunciante, Set denuncias) {
       this.idDenunciante = idDenunciante;
       this.denuncia = denuncia;
       this.nombreDenunciante = nombreDenunciante;
       this.correoDenunciante = correoDenunciante;
       this.telefonoDenunciante = telefonoDenunciante;
       this.denuncias = denuncias;
    }
   
    public BigDecimal getIdDenunciante() {
        return this.idDenunciante;
    }
    
    public void setIdDenunciante(BigDecimal idDenunciante) {
        this.idDenunciante = idDenunciante;
    }
    public Denuncia getDenuncia() {
        return this.denuncia;
    }
    
    public void setDenuncia(Denuncia denuncia) {
        this.denuncia = denuncia;
    }
    public String getNombreDenunciante() {
        return this.nombreDenunciante;
    }
    
    public void setNombreDenunciante(String nombreDenunciante) {
        this.nombreDenunciante = nombreDenunciante;
    }
    public String getCorreoDenunciante() {
        return this.correoDenunciante;
    }
    
    public void setCorreoDenunciante(String correoDenunciante) {
        this.correoDenunciante = correoDenunciante;
    }
    public String getTelefonoDenunciante() {
        return this.telefonoDenunciante;
    }
    
    public void setTelefonoDenunciante(String telefonoDenunciante) {
        this.telefonoDenunciante = telefonoDenunciante;
    }
    public Set getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set denuncias) {
        this.denuncias = denuncias;
    }




}


