package modelo.pojo;
// Generated 10-15-2016 03:51:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private BigDecimal idEstado;
     private Denuncia denuncia;
     private BigDecimal nombreEstado;
     private Set denuncias = new HashSet(0);

    public Estado() {
    }

	
    public Estado(BigDecimal idEstado, BigDecimal nombreEstado) {
        this.idEstado = idEstado;
        this.nombreEstado = nombreEstado;
    }
    public Estado(BigDecimal idEstado, Denuncia denuncia, BigDecimal nombreEstado, Set denuncias) {
       this.idEstado = idEstado;
       this.denuncia = denuncia;
       this.nombreEstado = nombreEstado;
       this.denuncias = denuncias;
    }
   
    public BigDecimal getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(BigDecimal idEstado) {
        this.idEstado = idEstado;
    }
    public Denuncia getDenuncia() {
        return this.denuncia;
    }
    
    public void setDenuncia(Denuncia denuncia) {
        this.denuncia = denuncia;
    }
    public BigDecimal getNombreEstado() {
        return this.nombreEstado;
    }
    
    public void setNombreEstado(BigDecimal nombreEstado) {
        this.nombreEstado = nombreEstado;
    }
    public Set getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set denuncias) {
        this.denuncias = denuncias;
    }




}


