package modelo.pojo;
// Generated 10-15-2016 03:51:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private BigDecimal idMunicipio;
     private Departamento departamento;
     private String nombreMunicipio;

    public Municipio() {
    }

	
    public Municipio(BigDecimal idMunicipio, String nombreMunicipio) {
        this.idMunicipio = idMunicipio;
        this.nombreMunicipio = nombreMunicipio;
    }
    public Municipio(BigDecimal idMunicipio, Departamento departamento, String nombreMunicipio) {
       this.idMunicipio = idMunicipio;
       this.departamento = departamento;
       this.nombreMunicipio = nombreMunicipio;
    }
   
    public BigDecimal getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(BigDecimal idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombreMunicipio() {
        return this.nombreMunicipio;
    }
    
    public void setNombreMunicipio(String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }




}


