package modelo.pojo;
// Generated 10-15-2016 03:51:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private BigDecimal idPersona;
     private Usuario usuario;
     private String correo;
     private String telefono;
     private String nombrePersona;
     private Set usuarios = new HashSet(0);

    public Persona() {
    }

	
    public Persona(BigDecimal idPersona, String correo, String telefono, String nombrePersona) {
        this.idPersona = idPersona;
        this.correo = correo;
        this.telefono = telefono;
        this.nombrePersona = nombrePersona;
    }
    public Persona(BigDecimal idPersona, Usuario usuario, String correo, String telefono, String nombrePersona, Set usuarios) {
       this.idPersona = idPersona;
       this.usuario = usuario;
       this.correo = correo;
       this.telefono = telefono;
       this.nombrePersona = nombrePersona;
       this.usuarios = usuarios;
    }
   
    public BigDecimal getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(BigDecimal idPersona) {
        this.idPersona = idPersona;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


