package modelo.pojo;
// Generated 10-15-2016 03:51:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private BigDecimal idRol;
     private Usuario usuario;
     private String nombreRol;
     private Set usuarios = new HashSet(0);

    public Rol() {
    }

	
    public Rol(BigDecimal idRol, String nombreRol) {
        this.idRol = idRol;
        this.nombreRol = nombreRol;
    }
    public Rol(BigDecimal idRol, Usuario usuario, String nombreRol, Set usuarios) {
       this.idRol = idRol;
       this.usuario = usuario;
       this.nombreRol = nombreRol;
       this.usuarios = usuarios;
    }
   
    public BigDecimal getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(BigDecimal idRol) {
        this.idRol = idRol;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


