package entity;
// Generated 26-oct-2016 13:59:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="CATEGORIA"
    ,schema="SYSTEM"
)
public class Categoria  implements java.io.Serializable {


     private BigDecimal idCategoria;
     private String nombreCategoria;
     private Set<Denuncia> denuncias = new HashSet<Denuncia>(0);

    public Categoria() {
    }

	
    public Categoria(BigDecimal idCategoria, String nombreCategoria) {
        this.idCategoria = idCategoria;
        this.nombreCategoria = nombreCategoria;
    }
    public Categoria(BigDecimal idCategoria, String nombreCategoria, Set<Denuncia> denuncias) {
       this.idCategoria = idCategoria;
       this.nombreCategoria = nombreCategoria;
       this.denuncias = denuncias;
    }
   
     @Id 

    
    @Column(name="ID_CATEGORIA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(BigDecimal idCategoria) {
        this.idCategoria = idCategoria;
    }

    
    @Column(name="NOMBRE_CATEGORIA", nullable=false, length=100)
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria")
    public Set<Denuncia> getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set<Denuncia> denuncias) {
        this.denuncias = denuncias;
    }




}


