package entity;
// Generated 26-oct-2016 13:59:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Denunciante generated by hbm2java
 */
@Entity
@Table(name="DENUNCIANTE"
    ,schema="SYSTEM"
)
public class Denunciante  implements java.io.Serializable {


     private BigDecimal idDenunciante;
     private String nombreDenunciante;
     private String correoDenunciante;
     private String telefonoDenunciante;
     private Set<Denuncia> denuncias = new HashSet<Denuncia>(0);

    public Denunciante() {
    }

	
    public Denunciante(BigDecimal idDenunciante, String nombreDenunciante, String correoDenunciante, String telefonoDenunciante) {
        this.idDenunciante = idDenunciante;
        this.nombreDenunciante = nombreDenunciante;
        this.correoDenunciante = correoDenunciante;
        this.telefonoDenunciante = telefonoDenunciante;
    }
    public Denunciante(BigDecimal idDenunciante, String nombreDenunciante, String correoDenunciante, String telefonoDenunciante, Set<Denuncia> denuncias) {
       this.idDenunciante = idDenunciante;
       this.nombreDenunciante = nombreDenunciante;
       this.correoDenunciante = correoDenunciante;
       this.telefonoDenunciante = telefonoDenunciante;
       this.denuncias = denuncias;
    }
   
     @Id 

    
    @Column(name="ID_DENUNCIANTE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdDenunciante() {
        return this.idDenunciante;
    }
    
    public void setIdDenunciante(BigDecimal idDenunciante) {
        this.idDenunciante = idDenunciante;
    }

    
    @Column(name="NOMBRE_DENUNCIANTE", nullable=false, length=50)
    public String getNombreDenunciante() {
        return this.nombreDenunciante;
    }
    
    public void setNombreDenunciante(String nombreDenunciante) {
        this.nombreDenunciante = nombreDenunciante;
    }

    
    @Column(name="CORREO_DENUNCIANTE", nullable=false, length=50)
    public String getCorreoDenunciante() {
        return this.correoDenunciante;
    }
    
    public void setCorreoDenunciante(String correoDenunciante) {
        this.correoDenunciante = correoDenunciante;
    }

    
    @Column(name="TELEFONO_DENUNCIANTE", nullable=false, length=10)
    public String getTelefonoDenunciante() {
        return this.telefonoDenunciante;
    }
    
    public void setTelefonoDenunciante(String telefonoDenunciante) {
        this.telefonoDenunciante = telefonoDenunciante;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="denunciante")
    public Set<Denuncia> getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set<Denuncia> denuncias) {
        this.denuncias = denuncias;
    }




}


