package entity;
// Generated 26-oct-2016 13:59:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name="ESTADO"
    ,schema="SYSTEM"
)
public class Estado  implements java.io.Serializable {


     private BigDecimal idEstado;
     private String nombreEstado;
     private Set<Denuncia> denuncias = new HashSet<Denuncia>(0);

    public Estado() {
    }

	
    public Estado(BigDecimal idEstado, String nombreEstado) {
        this.idEstado = idEstado;
        this.nombreEstado = nombreEstado;
    }
    public Estado(BigDecimal idEstado, String nombreEstado, Set<Denuncia> denuncias) {
       this.idEstado = idEstado;
       this.nombreEstado = nombreEstado;
       this.denuncias = denuncias;
    }
   
     @Id 

    
    @Column(name="ID_ESTADO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(BigDecimal idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="NOMBRE_ESTADO", nullable=false, length=100)
    public String getNombreEstado() {
        return this.nombreEstado;
    }
    
    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estado")
    public Set<Denuncia> getDenuncias() {
        return this.denuncias;
    }
    
    public void setDenuncias(Set<Denuncia> denuncias) {
        this.denuncias = denuncias;
    }




}


