package entity;
// Generated 26-oct-2016 13:59:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name="MUNICIPIO"
    ,schema="SYSTEM"
)
public class Municipio  implements java.io.Serializable {


     private BigDecimal idMunicipio;
     private Departamento departamento;
     private String nombreMunicipio;

    public Municipio() {
    }

    public Municipio(BigDecimal idMunicipio, Departamento departamento, String nombreMunicipio) {
       this.idMunicipio = idMunicipio;
       this.departamento = departamento;
       this.nombreMunicipio = nombreMunicipio;
    }
   
     @Id 

    
    @Column(name="ID_MUNICIPIO", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(BigDecimal idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DEPARTAMENTO", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="NOMBRE_MUNICIPIO", nullable=false, length=50)
    public String getNombreMunicipio() {
        return this.nombreMunicipio;
    }
    
    public void setNombreMunicipio(String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }




}


