package entity;
// Generated 26-oct-2016 13:59:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="PERSONA"
    ,schema="SYSTEM"
)
public class Persona  implements java.io.Serializable {


     private BigDecimal idPersona;
     private Usuario usuario;
     private String correo;
     private String telefono;
     private String nombrePersona;

    public Persona() {
    }

    public Persona(BigDecimal idPersona, Usuario usuario, String correo, String telefono, String nombrePersona) {
       this.idPersona = idPersona;
       this.usuario = usuario;
       this.correo = correo;
       this.telefono = telefono;
       this.nombrePersona = nombrePersona;
    }
   
     @Id 

    
    @Column(name="ID_PERSONA", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(BigDecimal idPersona) {
        this.idPersona = idPersona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NOMBRE", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="CORREO", nullable=false, length=50)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="TELEFONO", nullable=false, length=10)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="NOMBRE_PERSONA", nullable=false, length=50)
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }




}


