package entity;
// Generated 26-oct-2016 13:59:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="USUARIO"
    ,schema="SYSTEM"
)
public class Usuario  implements java.io.Serializable {


     private String nombre;
     private Rol rol;
     private String contrasena;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Usuario() {
    }

	
    public Usuario(String nombre, Rol rol, String contrasena) {
        this.nombre = nombre;
        this.rol = rol;
        this.contrasena = contrasena;
    }
    public Usuario(String nombre, Rol rol, String contrasena, Set<Persona> personas) {
       this.nombre = nombre;
       this.rol = rol;
       this.contrasena = contrasena;
       this.personas = personas;
    }
   
     @Id 

    
    @Column(name="NOMBRE", unique=true, nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ROL", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    
    @Column(name="CONTRASENA", nullable=false, length=16)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


